src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="Reclamation")
 * @ORM\Entity(repositoryClass=ReclamationRepository::class)
 */
class Reclamation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Immatriculation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Responsable ;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Desciption;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $etat;

    public function getImmatriculation(): ?string
    {
        return $this->Immatriculation;
    }

    public function setImmatriculation(string $Immatriculation): self
    {
        $this->Immatriculation = $Immatriculation;

        return $this;
    }

    public function getDesciption(): ?string
    {
        return $this->Desciption;
    }

    public function setDesciption(string $Desciption): self
    {
        $this->Desciption = $Desciption;

        return $this;
    }

    public function getResponsable(): ?string
    {
        return $this->Responsable;
    }

    public function setResponsable(string $Responsable): self
    {
        $this->Responsable = $Responsable;

        return $this;
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
    public function getemail(): ?string
    {
        return $this->email;
    }

    public function setemail(string $email): self
    {
        $this->email = $email;

        return $this;
    }



    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', null, [
                'attr' => ['class' => 'form-control'],
                ])
            ->add('prenom', null, [
                'attr' => ['class' => 'form-control'],
                ])
            ->add('email', null, [
                'attr' => ['class' => 'form-control'],
                ])
            ->add('Immatriculation', null, [
                'attr' => ['class' => 'form-control'],
                ])
            ->add('tel', null, [
                'attr' => ['class' => 'form-control'],
                ])

            ->add('Desciption', TextareaType::class, [
                'attr' => ['class' => 'tinymce'],
            ])

            ->add('Responsable',ChoiceType::class, [
                'choices'  => [
                    'Expert en sinistre' => 'Expert en sinistre',
                    'conseiller' => 'conseiller',
                ], 'attr' => ['class' => 'form-control'],
                'required' => true,
                'label' => false ,
           
                ]);
            
      
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Contrat;
use App\Entity\DemandeCreationContrat;
use App\Entity\Reclamation;
use App\Form\ReclamationType;
use App\Repository\ReclamationRepository;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/Reclamation")
 */
class ReclamationController extends AbstractController
{
    /**
     * @Route("/", name="Reclamation_index", methods={"GET"})
     */
    public function index(ReclamationRepository $ReclamationRepository): Response
    {

        return $this->render('Reclamation/index.html.twig', [
            'Reclamation' => $ReclamationRepository->findAll(),
        ]);

    }

    /**
     * @Route("/Rec", name="Reclamation_indexx", methods={"GET"})
     */
    public function indexx(ReclamationRepository $ReclamationRepository): Response
    {

        return $this->render('Reclamation/indexx.html.twig', [
            'Reclamation' => $ReclamationRepository->findAll(),
        ]);

    }

    /**
     * @Route("/new", name="Reclamation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $Reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $Reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($Reclamation);
            $entityManager->flush();
            $this ->addFlash( 'info' , 'Réclamation envoyée!');

        }

        return $this->render('Reclamation/new.html.twig', [
            'Reclamation' => $Reclamation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="Reclamation_show", methods={"GET"})
     */
    public function show(Reclamation $Reclamation): Response
    {
        return $this->render('Reclamation/show.html.twig', [
            'Reclamation' => $Reclamation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="Reclamation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reclamation $Reclamation): Response
    {
        $form = $this->createForm(ReclamationType::class, $Reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('Reclamation_index');
        }

        return $this->render('Reclamation/edit.html.twig', [
            'Reclamation' => $Reclamation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="Reclamation_delete")
     */
    public function delete(Reclamation $Reclamation): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($Reclamation);
        $entityManager->flush();


        return $this->redirectToRoute('Reclamation_index');
    }

    /**
     * @Route("/{id}/pdf", name="Reclamation_pdf", methods={"GET"})
     */
    public function pdf(Reclamation $Reclamation): Response
    {
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);

        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('Reclamation/pdf.html.twig', [
            'Reclamation' => $Reclamation,
        ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("Reclamation.pdf", [
            "Attachment" => true
        ]);
    }

    /**
     * @Route("/{id}/refuser", name="Reclamation_refuser", methods={"GET"})
     */
    public function refuser(Request $request, $id)
    {
        $Reclamation = $this->getDoctrine()
            ->getRepository(Reclamation::class)
            ->find($id);


        $Reclamation->setEtat("refusée");

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($Reclamation);
        $entityManager->flush();

return $this->redirectToRoute('Reclamation_index');
}

    /**
     * @Route("/{id}/valider", name="Reclamation_valider", methods={"GET"})
     */
    public function Valider (Request $request, $id)
    {
        $Reclamation = $this->getDoctrine()
            ->getRepository(Reclamation::class)
            ->find($id);


        $Reclamation->setEtat("validée");

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($Reclamation);
        $entityManager->flush();
        return $this->redirectToRoute('Reclamation_index');

    }

    /**
     * @Route("/CAl/cal", name="Calender_index", methods={"GET"})
     */
    public function cal()
    {
        return $this->render('calendar/index.html.twig', [
            'Calenders' => 'ReclamationController',
        ]);
    }
}

templates/Reclamation/_delete_form.html.twig
<form method="post" action="{{ path('Reclamation_delete', {'id': Reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ Reclamation.id) }}">
    <button class="btn btn-danger btn-sm"><i class="fas fa-trash">
    </i>Supprimer</button>
</form>

templates/Reclamation/_form.html.twig
{{ form_start(form) }}

                               <label>Nom *</label>
                               {{ form_widget(form.nom) }}
                            <label>Prenom *</label>
                            {{ form_widget(form.prenom) }}

<label>Email *</label>
{{ form_widget(form.email) }}



                             <label>téléphone</label>
                             {{ form_widget(form.tel) }}

<label>Immatriculation</label>
{{ form_widget(form.Immatriculation) }}
<label>Responsable</label>
{{ form_widget(form.Responsable) }}
<br>
<label>Desciption</label>
<br>
{{ form_widget(form.Desciption) }}





     <br>

        <button style ="font-size: 1.475rem;margin-bottom: 10px" class="btn btn-info btn-sm">{{ button_label|default('Enregistrer') }}  </button>



{{ form_end(form) }}

templates/Reclamation/edit.html.twig
{% extends 'templateAdmine/adminebase.html.twig' %}

{% block body %}
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            </div>
            <div class="page-content">
                <h1> Modifier Assure</h1>

                {{ include('Reclamation/_form.html.twig') }}
                <br>
                <a class="btn btn-xs btn-danger" href="{{ path('Reclamation_index') }}">
                    Annuler
                </a>
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->
{% endblock %}

templates/Reclamation/index.html.twig
{% extends 'templateAdmine/adminebase.html.twig' %}
{% block body %}
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">Tables</a>
                    </li>
                </ul>
            </div>
            <div class="page-content">
                <div class="page-header">
                    <h1>
                        Réclamations
                        <small>
                            <i class="ace-icon fa fa-angle-double-right"></i>
                        </small>
                    </h1>
                    <br>

                </div><!-- /.page-header -->
                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->
                        <div class="row">
                            <div class="col-xs-12">

                      <table id="example1" class="table table-bordered table-striped">

                        <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Prenom</th>
                            <th>Email</th>
                            <th>Téléphone</th>
                            <th>Immatriuclation</th>
                            <th>Destinataire</th>
                            <th>Etat</th>


                            <th>actions</th>
                        </tr>
                        </thead>
                        <tbody>
                         
                            {% for Reclamation in Reclamation %}
                          <tr>
                            <td class="sorting_1 dtr-control" tabindex="0">{{ Reclamation.nom }}</td>
                            <td>{{ Reclamation.prenom }}</td>
                              <td>{{ Reclamation.email }}</td>
                              <td>{{ Reclamation.tel }}</td>
                            <td>{{ Reclamation.Immatriculation }}</td>

                            <td>{{ Reclamation.Responsable }}</td>
                              <td>{{ Reclamation.etat }}</td>

                            <td>

                                <div class="hidden-sm hidden-xs btn-group">
                                    <a class="btn btn-xs btn-danger" href="{{ path('Reclamation_delete', {'id': Reclamation.id}) }}">
                                        <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                    </a>
                                </div>
                                <div class="hidden-sm hidden-xs btn-group">
                                    <a class="btn btn-xs btn-danger" href="{{ path('Reclamation_show', {'id': Reclamation.id}) }}">
                                        <i class="ace-icon fa fa-check-square-o"></i>
                                    </a>
                                </div>
                                

                            </td>
                        <</tr>
                        {% endfor %}
                        </tbody>

                      </table>
                            </div><!-- /.span -->
                        </div><!-- /.row -->
                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->
{% endblock %}

templates/Reclamation/indexx.html.twig
{% extends 'templateAdmine/adminebase.html.twig' %}
{% block body %}
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">Tables</a>
                    </li>
                </ul>
            </div>
            <div class="page-content">
                <div class="page-header">
                    <h1>
                        Réclamations
                        <small>
                            <i class="ace-icon fa fa-angle-double-right"></i>
                        </small>
                    </h1>
                    <br>

                </div><!-- /.page-header -->
                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->
                        <div class="row">
                            <div class="col-xs-12">

                      <table id="example1" class="table table-bordered table-striped">

                        <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Prenom</th>
                            <th>Email</th>
                            <th>Téléphone</th>
                            <th>Immatriuclation</th>
                            <th>Destinataire</th>
                            <th>Etat</th>


                        </tr>
                        </thead>
                        <tbody>
                         
                            {% for Reclamation in Reclamation %}
                          <tr>
                            <td class="sorting_1 dtr-control" tabindex="0">{{ Reclamation.nom }}</td>
                            <td>{{ Reclamation.prenom }}</td>
                              <td>{{ Reclamation.email }}</td>
                              <td>{{ Reclamation.tel }}</td>
                            <td>{{ Reclamation.Immatriculation }}</td>

                            <td>{{ Reclamation.Responsable }}</td>
                              <td>{{ Reclamation.etat }}</td>


                        <</tr>
                        {% endfor %}
                        </tbody>

                      </table>
                            </div><!-- /.span -->
                        </div><!-- /.row -->
                        <!-- PAGE CONTENT ENDS -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->
{% endblock %}

templates/Reclamation/new.html.twig
{% extends 'templateAdmine/adminebase.html.twig' %}

{% block body %}
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            </div>
            {% for message in app.flashes('info') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
            {% endfor %}
            <div class="page-content">
                <h1> Créer une réclamation </h1>

                {{ include('Reclamation/_form.html.twig') }}
                <br>
                <a class="btn btn-xs btn-danger" href="{{ path('Reclamation_index') }}">
                    Annuler
                </a>
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->
{% endblock %}

templates/Reclamation/pdf.html.twig
{% block content %}
<h1 align="center">Réclamation  </h1>
<body >
    <table class="border" width="60%" align="center" >
        <tbody>
        
        <tr>
            <th>Nom </th>
            <td>{{ Reclamation.nom }}</td>

        </tr>
        <tr>
            <th>prenom</th>
            <td>{{ Reclamation.prenom }}</td>
        </tr>


        <tr>
            <th>email</th>
            <td>{{ Reclamation.email }}</td>
        </tr>

        <tr>
            <th>Immatriculation</th>
            <td>{{ Reclamation.Immatriculation }}</td>
        </tr>
       <tr>
            <th>tel</th>
            <td>{{ Reclamation.tel }}</td>
        </tr>
        <tr>
            <th>Immatriculation</th>
            <td>{{ Reclamation.immatriculation }}</td>
        </tr>
        <tr>
            <th>Responsable</th>
            <td>{{ Reclamation.Responsable }}</td>
        </tr>


        <tr>
            <th>Desciption</th>
            <td>{{ Reclamation.Desciption }}</td>

        </tr>


        </tbody>
    </table>


{% endblock %}

templates/Reclamation/show.html.twig
{% extends 'templateAdmine/adminebase.html.twig' %}

            {% block body %}



                <div class="main-content">
                <div class="main-content-inner">
                <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                    <ul class="breadcrumb">
                        <li>
                            <i class="ace-icon fa fa-home home-icon"></i>
                            <a href="#">Home</a>
                        </li>

                        <li>
                            <a href="#">More Pages</a>
                        </li>
                        <li class="active">User Profile</li>
                    </ul><!-- /.breadcrumb -->

                    <div class="nav-search" id="nav-search">
                        <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input"
                                           id="nav-search-input" autocomplete="off"/>
									<i class="ace-icon fa fa-search nav-search-icon"></i>
								</span>
                        </form>
                    </div><!-- /.nav-search -->
                </div>

                <div class="page-content">
                <div class="ace-settings-container" id="ace-settings-container">
                    <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
                        <i class="ace-icon fa fa-cog bigger-130"></i>
                    </div>

                    <div class="ace-settings-box clearfix" id="ace-settings-box">
                        <div class="pull-left width-50">


                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state"
                                       id="ace-settings-navbar" autocomplete="off"/>
                                <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state"
                                       id="ace-settings-sidebar" autocomplete="off"/>
                                <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state"
                                       id="ace-settings-breadcrumbs" autocomplete="off"/>
                                <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl"
                                       autocomplete="off"/>
                                <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2 ace-save-state"
                                       id="ace-settings-add-container" autocomplete="off"/>
                                <label class="lbl" for="ace-settings-add-container">
                                    Inside
                                    <b>.container</b>
                                </label>
                            </div>
                        </div><!-- /.pull-left -->

                        <div class="pull-left width-50">
                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-hover"
                                       autocomplete="off"/>
                                <label class="lbl" for="ace-settings-hover"> Submenu on Hover</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-compact"
                                       autocomplete="off"/>
                                <label class="lbl" for="ace-settings-compact"> Compact Sidebar</label>
                            </div>

                            <div class="ace-settings-item">
                                <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-highlight"
                                       autocomplete="off"/>
                                <label class="lbl" for="ace-settings-highlight"> Alt. Active Item</label>
                            </div>
                        </div><!-- /.pull-left -->
                    </div><!-- /.ace-settings-box -->
                </div><!-- /.ace-settings-container -->


                <div class="page-header">
                    <h1>
                        Détail réclamation

                    </h1>
                </div><!-- /.page-header -->




                <div>


                    {% if is_granted('ROLE_AGENT') %}


                        <a class="btn btn-xs btn-success" style="margin-right: 20px;"
                           href="{{ path('Reclamation_valider' , {'id': Reclamation.id}) }}">
                            Valider
                        </a>

                        <a class="btn btn-xs btn-danger" style="margin-right: 20px;"
                           href="{{ path('Reclamation_refuser' , {'id': Reclamation.id}) }}">
                            Refuser
                        </a>




                    {% endif %}


                </div>

                <div class="hr dotted"></div>

                <div>

                <div class="col-xs-12 col-sm-4 ">
                    <div>
												<span class="profile-picture">


                        <div class="space-4"></div>

                        <div class="width-80 label label-info label-xlg arrowed-in arrowed-in-right">
                            <div class="inline position-relative">
                                <a href="#" class="user-title-label dropdown-toggle" data-toggle="dropdown">
                                    <i class="ace-icon fa fa-circle light-green"></i>
                                    &nbsp;
                                    <span class="white">{{ Reclamation.nom }} {{ Reclamation.prenom }}</span>


                                </a>

                                <ul class="align-left dropdown-menu dropdown-caret dropdown-lighter">
                                    <li class="dropdown-header"> Change Status</li>

                                    <li>
                                        <a href="#">
                                            <i class="ace-icon fa fa-circle green"></i>
                                            &nbsp;
                                            <span class="green">Available</span>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <i class="ace-icon fa fa-circle red"></i>
                                            &nbsp;
                                            <span class="red">Busy</span>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <i class="ace-icon fa fa-circle grey"></i>
                                            &nbsp;
                                            <span class="grey">Invisible</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>


                    <div class="space-6"></div>

                    <div class="profile-contact-info">
                        <div class="profile-contact-links align-left">
                        </div>

                        <div class="space-6"></div>

                        <div class="profile-social-links align-center">
                        </div>
                    </div>





                <div class="col-xs-12 col-sm-9">
                <div class="space-12"></div>
                <div class="profile-user-info profile-user-info-striped">

                    <div class="profile-info-row">
                        <div class="profile-info-name"> Immatriculation </div>

                        <div class="profile-info-value">
                            <span>{{ Reclamation.Immatriculation }}</span>
                        </div>
                    </div>

                    <div class="profile-info-row">
                        <div class="profile-info-name"> Mobile </div>
                        <div class="profile-info-value">
                            <span> {{ Reclamation.tel }}</span>
                        </div>
                    </div>

                    <div class="profile-info-row">
                        <div class="profile-info-name"> Email</div>
                        <div class="profile-info-value">
                            <span>{{ Reclamation.email }}</span>
                        </div>
                    </div>
                </div>
                <br><br>
                <FONT size="4"> <strong> <div style="color:#0088ff;">
          <tr>
                <th>Description : </th>
                    <br>
          </div>
                </strong>
                </FONT>
                <td>{{ Reclamation.Desciption }}</td>
            </tr>



            {% endblock %}